function [BW,maskedRGBImage] = createMask_pink(RGB)
%%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder app. The colorspace and
%  range for each channel of the colorspace were set within the app. The
%  segmentation mask is returned in BW, and a composite of the mask and
%  original RGB images is returned in maskedRGBImage.

% Auto-generated by colorThresholder app on 10-Sep-2019
%------------------------------------------------------


% Convert RGB image to chosen color space
I = rgb2hsv(RGB);

% Define thresholds for channel 1 based on histogram settings
channel1Min = 0.0;
channel1smallMax=0.15;
channel1smallMin=0.75;
channel1Max = 1.0;

% Define thresholds for channel 2 based on histogram settings
channel2Min = 0.150;
channel2Max = 1.000;

% Define thresholds for channel 3 based on histogram settings
channel3Min = 0.575;
channel3Max = 1.000;


% Preallocation testen. evtl speedup
% Create mask based on chosen histogram thresholds
sliderBW = xor((I(:,:,1) >= channel1Min & I(:,:,1) <= channel1smallMax ) ...
    ,(I(:,:,1) >= channel1smallMin & I(:,:,1) <= channel1Max)) & ...
    (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
    (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);
BW = sliderBW;

% Initialize output masked image based on input image.
maskedRGBImage = RGB;

% Set background pixels where BW is false to zero.
maskedRGBImage(repmat(~BW,[1 1 3])) = 255;

end
